#!/bin/bash
# 主要是針對designer資料夾內的*.ui,將其轉換成*.py程式碼
#
# generate python files based on the designer ui files. pyuic4 and pyrcc4
# should be on the path.
#

if [ ! -d "designer" ]
then
    echo "Please run this from the project root"
    exit
fi
#需在主目錄下執行./tools/build_ui.sh

mkdir -p aqt/forms
# -p that means no error if existing, make parent directories as needed.

init=aqt/forms/__init__.py
temp=aqt/forms/scratch
rm -f $init $temp
# 假設原有目錄下有 __init__.py 與 scratch檔案將其強制刪除
echo "# This file auto-generated by build_ui.sh. Don't edit." > $init
echo "__all__ = [" >> $init
# 變數$init 內容為
# This file auto-generated by build_ui.sh. Don't edit.
# __all__ = [

echo "Generating forms.."
for i in designer/*.ui
#目前在主目錄下執行, i 為 designer目錄下的每一個 ui檔
do
    base=$(basename $i .ui)
    py="aqt/forms/${base}.py"
    echo "	\"$base\"," >> $init
    echo "import $base" >> $temp
    if [ $i -nt $py ]; then
        echo " * "$py
        pyuic4 $i -o $py
        # munge the output to use gettext
        perl -pi.bak -e 's/(QtGui\.QApplication\.)?_?translate\(".*?", /_(/; s/, None.*/))/' $py
        rm $py.bak
    fi
done
echo "]" >> $init
cat $temp >> $init
# $init 為aqt/forms/__init__.py  

#rm $temp
# $temp為scratch,其內容如下
#import about
#import addcards
#import addfield
#import addmodel
#import browserdisp
#import browseropts


echo "Building resources.."
pyrcc4 designer/icons.qrc -o aqt/forms/icons_rc.py
#將 icons圖示資料庫 轉換成 py程式碼
